{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "obelus.fullname" . }}
  labels:
    {{- include "obelus.labels" . | nindent 4 }}
type: Opaque
stringData:
  auth-token-secret: {{ .Values.secrets.authTokenSecret | quote }}
  cookie-secret: {{ .Values.secrets.cookieSecret | quote }}
  hardcover-api-token: {{ .Values.secrets.hardcoverApiToken | quote }}
  database-url: {{ include "obelus.databaseUrl" . | quote }}
{{- end }}
