/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as UUserNameRouteImport } from './routes/u/$userName'
import { Route as LayoutAuthRouteImport } from './routes/_layout/auth'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as LayoutAuthenticatedIndexRouteImport } from './routes/_layout/_authenticated/index'
import { Route as LayoutAuthLoginRouteImport } from './routes/_layout/auth/login'
import { Route as LayoutAuthenticatedSettingsRouteImport } from './routes/_layout/_authenticated/settings'
import { Route as LayoutAuthenticatedReadRouteImport } from './routes/_layout/_authenticated/read'
import { Route as LayoutAuthenticatedPlannedRouteImport } from './routes/_layout/_authenticated/planned'
import { Route as LayoutAuthRegisterChar123TokenChar125RouteImport } from './routes/_layout/auth/register.{-$token}'
import { Route as LayoutAuthenticatedSettingsUsersRouteImport } from './routes/_layout/_authenticated/settings/users'
import { Route as LayoutAuthenticatedSettingsInviteLinksRouteImport } from './routes/_layout/_authenticated/settings/invite-links'
import { Route as LayoutAuthenticatedSettingsImportsRouteImport } from './routes/_layout/_authenticated/settings/imports'
import { Route as LayoutAuthenticatedSettingsConfigRouteImport } from './routes/_layout/_authenticated/settings/config'
import { Route as LayoutAuthenticatedSeriesSeriesIdRouteImport } from './routes/_layout/_authenticated/series/$seriesId'
import { Route as LayoutAuthenticatedBookBookIdRouteImport } from './routes/_layout/_authenticated/book/$bookId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserNameRoute = UUserNameRouteImport.update({
  id: '/u/$userName',
  path: '/u/$userName',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAuthRoute = LayoutAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedIndexRoute =
  LayoutAuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthLoginRoute = LayoutAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutAuthRoute,
} as any)
const LayoutAuthenticatedSettingsRoute =
  LayoutAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedReadRoute = LayoutAuthenticatedReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => LayoutAuthenticatedRoute,
} as any)
const LayoutAuthenticatedPlannedRoute =
  LayoutAuthenticatedPlannedRouteImport.update({
    id: '/planned',
    path: '/planned',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthRegisterChar123TokenChar125Route =
  LayoutAuthRegisterChar123TokenChar125RouteImport.update({
    id: '/register/{-$token}',
    path: '/register/{-$token}',
    getParentRoute: () => LayoutAuthRoute,
  } as any)
const LayoutAuthenticatedSettingsUsersRoute =
  LayoutAuthenticatedSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => LayoutAuthenticatedSettingsRoute,
  } as any)
const LayoutAuthenticatedSettingsInviteLinksRoute =
  LayoutAuthenticatedSettingsInviteLinksRouteImport.update({
    id: '/invite-links',
    path: '/invite-links',
    getParentRoute: () => LayoutAuthenticatedSettingsRoute,
  } as any)
const LayoutAuthenticatedSettingsImportsRoute =
  LayoutAuthenticatedSettingsImportsRouteImport.update({
    id: '/imports',
    path: '/imports',
    getParentRoute: () => LayoutAuthenticatedSettingsRoute,
  } as any)
const LayoutAuthenticatedSettingsConfigRoute =
  LayoutAuthenticatedSettingsConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => LayoutAuthenticatedSettingsRoute,
  } as any)
const LayoutAuthenticatedSeriesSeriesIdRoute =
  LayoutAuthenticatedSeriesSeriesIdRouteImport.update({
    id: '/series/$seriesId',
    path: '/series/$seriesId',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedBookBookIdRoute =
  LayoutAuthenticatedBookBookIdRouteImport.update({
    id: '/book/$bookId',
    path: '/book/$bookId',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutAuthenticatedIndexRoute
  '/auth': typeof LayoutAuthRouteWithChildren
  '/u/$userName': typeof UUserNameRoute
  '/planned': typeof LayoutAuthenticatedPlannedRoute
  '/read': typeof LayoutAuthenticatedReadRoute
  '/settings': typeof LayoutAuthenticatedSettingsRouteWithChildren
  '/auth/login': typeof LayoutAuthLoginRoute
  '/book/$bookId': typeof LayoutAuthenticatedBookBookIdRoute
  '/series/$seriesId': typeof LayoutAuthenticatedSeriesSeriesIdRoute
  '/settings/config': typeof LayoutAuthenticatedSettingsConfigRoute
  '/settings/imports': typeof LayoutAuthenticatedSettingsImportsRoute
  '/settings/invite-links': typeof LayoutAuthenticatedSettingsInviteLinksRoute
  '/settings/users': typeof LayoutAuthenticatedSettingsUsersRoute
  '/auth/register/{-$token}': typeof LayoutAuthRegisterChar123TokenChar125Route
}
export interface FileRoutesByTo {
  '/': typeof LayoutAuthenticatedIndexRoute
  '/auth': typeof LayoutAuthRouteWithChildren
  '/u/$userName': typeof UUserNameRoute
  '/planned': typeof LayoutAuthenticatedPlannedRoute
  '/read': typeof LayoutAuthenticatedReadRoute
  '/settings': typeof LayoutAuthenticatedSettingsRouteWithChildren
  '/auth/login': typeof LayoutAuthLoginRoute
  '/book/$bookId': typeof LayoutAuthenticatedBookBookIdRoute
  '/series/$seriesId': typeof LayoutAuthenticatedSeriesSeriesIdRoute
  '/settings/config': typeof LayoutAuthenticatedSettingsConfigRoute
  '/settings/imports': typeof LayoutAuthenticatedSettingsImportsRoute
  '/settings/invite-links': typeof LayoutAuthenticatedSettingsInviteLinksRoute
  '/settings/users': typeof LayoutAuthenticatedSettingsUsersRoute
  '/auth/register/{-$token}': typeof LayoutAuthRegisterChar123TokenChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/_layout/auth': typeof LayoutAuthRouteWithChildren
  '/u/$userName': typeof UUserNameRoute
  '/_layout/_authenticated/planned': typeof LayoutAuthenticatedPlannedRoute
  '/_layout/_authenticated/read': typeof LayoutAuthenticatedReadRoute
  '/_layout/_authenticated/settings': typeof LayoutAuthenticatedSettingsRouteWithChildren
  '/_layout/auth/login': typeof LayoutAuthLoginRoute
  '/_layout/_authenticated/': typeof LayoutAuthenticatedIndexRoute
  '/_layout/_authenticated/book/$bookId': typeof LayoutAuthenticatedBookBookIdRoute
  '/_layout/_authenticated/series/$seriesId': typeof LayoutAuthenticatedSeriesSeriesIdRoute
  '/_layout/_authenticated/settings/config': typeof LayoutAuthenticatedSettingsConfigRoute
  '/_layout/_authenticated/settings/imports': typeof LayoutAuthenticatedSettingsImportsRoute
  '/_layout/_authenticated/settings/invite-links': typeof LayoutAuthenticatedSettingsInviteLinksRoute
  '/_layout/_authenticated/settings/users': typeof LayoutAuthenticatedSettingsUsersRoute
  '/_layout/auth/register/{-$token}': typeof LayoutAuthRegisterChar123TokenChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/u/$userName'
    | '/planned'
    | '/read'
    | '/settings'
    | '/auth/login'
    | '/book/$bookId'
    | '/series/$seriesId'
    | '/settings/config'
    | '/settings/imports'
    | '/settings/invite-links'
    | '/settings/users'
    | '/auth/register/{-$token}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/u/$userName'
    | '/planned'
    | '/read'
    | '/settings'
    | '/auth/login'
    | '/book/$bookId'
    | '/series/$seriesId'
    | '/settings/config'
    | '/settings/imports'
    | '/settings/invite-links'
    | '/settings/users'
    | '/auth/register/{-$token}'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_authenticated'
    | '/_layout/auth'
    | '/u/$userName'
    | '/_layout/_authenticated/planned'
    | '/_layout/_authenticated/read'
    | '/_layout/_authenticated/settings'
    | '/_layout/auth/login'
    | '/_layout/_authenticated/'
    | '/_layout/_authenticated/book/$bookId'
    | '/_layout/_authenticated/series/$seriesId'
    | '/_layout/_authenticated/settings/config'
    | '/_layout/_authenticated/settings/imports'
    | '/_layout/_authenticated/settings/invite-links'
    | '/_layout/_authenticated/settings/users'
    | '/_layout/auth/register/{-$token}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  UUserNameRoute: typeof UUserNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$userName': {
      id: '/u/$userName'
      path: '/u/$userName'
      fullPath: '/u/$userName'
      preLoaderRoute: typeof UUserNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/auth': {
      id: '/_layout/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof LayoutAuthRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated/': {
      id: '/_layout/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/auth/login': {
      id: '/_layout/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof LayoutAuthLoginRouteImport
      parentRoute: typeof LayoutAuthRoute
    }
    '/_layout/_authenticated/settings': {
      id: '/_layout/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/read': {
      id: '/_layout/_authenticated/read'
      path: '/read'
      fullPath: '/read'
      preLoaderRoute: typeof LayoutAuthenticatedReadRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/planned': {
      id: '/_layout/_authenticated/planned'
      path: '/planned'
      fullPath: '/planned'
      preLoaderRoute: typeof LayoutAuthenticatedPlannedRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/auth/register/{-$token}': {
      id: '/_layout/auth/register/{-$token}'
      path: '/register/{-$token}'
      fullPath: '/auth/register/{-$token}'
      preLoaderRoute: typeof LayoutAuthRegisterChar123TokenChar125RouteImport
      parentRoute: typeof LayoutAuthRoute
    }
    '/_layout/_authenticated/settings/users': {
      id: '/_layout/_authenticated/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsUsersRouteImport
      parentRoute: typeof LayoutAuthenticatedSettingsRoute
    }
    '/_layout/_authenticated/settings/invite-links': {
      id: '/_layout/_authenticated/settings/invite-links'
      path: '/invite-links'
      fullPath: '/settings/invite-links'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsInviteLinksRouteImport
      parentRoute: typeof LayoutAuthenticatedSettingsRoute
    }
    '/_layout/_authenticated/settings/imports': {
      id: '/_layout/_authenticated/settings/imports'
      path: '/imports'
      fullPath: '/settings/imports'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsImportsRouteImport
      parentRoute: typeof LayoutAuthenticatedSettingsRoute
    }
    '/_layout/_authenticated/settings/config': {
      id: '/_layout/_authenticated/settings/config'
      path: '/config'
      fullPath: '/settings/config'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsConfigRouteImport
      parentRoute: typeof LayoutAuthenticatedSettingsRoute
    }
    '/_layout/_authenticated/series/$seriesId': {
      id: '/_layout/_authenticated/series/$seriesId'
      path: '/series/$seriesId'
      fullPath: '/series/$seriesId'
      preLoaderRoute: typeof LayoutAuthenticatedSeriesSeriesIdRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/book/$bookId': {
      id: '/_layout/_authenticated/book/$bookId'
      path: '/book/$bookId'
      fullPath: '/book/$bookId'
      preLoaderRoute: typeof LayoutAuthenticatedBookBookIdRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
  }
}

interface LayoutAuthenticatedSettingsRouteChildren {
  LayoutAuthenticatedSettingsConfigRoute: typeof LayoutAuthenticatedSettingsConfigRoute
  LayoutAuthenticatedSettingsImportsRoute: typeof LayoutAuthenticatedSettingsImportsRoute
  LayoutAuthenticatedSettingsInviteLinksRoute: typeof LayoutAuthenticatedSettingsInviteLinksRoute
  LayoutAuthenticatedSettingsUsersRoute: typeof LayoutAuthenticatedSettingsUsersRoute
}

const LayoutAuthenticatedSettingsRouteChildren: LayoutAuthenticatedSettingsRouteChildren =
  {
    LayoutAuthenticatedSettingsConfigRoute:
      LayoutAuthenticatedSettingsConfigRoute,
    LayoutAuthenticatedSettingsImportsRoute:
      LayoutAuthenticatedSettingsImportsRoute,
    LayoutAuthenticatedSettingsInviteLinksRoute:
      LayoutAuthenticatedSettingsInviteLinksRoute,
    LayoutAuthenticatedSettingsUsersRoute:
      LayoutAuthenticatedSettingsUsersRoute,
  }

const LayoutAuthenticatedSettingsRouteWithChildren =
  LayoutAuthenticatedSettingsRoute._addFileChildren(
    LayoutAuthenticatedSettingsRouteChildren,
  )

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedPlannedRoute: typeof LayoutAuthenticatedPlannedRoute
  LayoutAuthenticatedReadRoute: typeof LayoutAuthenticatedReadRoute
  LayoutAuthenticatedSettingsRoute: typeof LayoutAuthenticatedSettingsRouteWithChildren
  LayoutAuthenticatedIndexRoute: typeof LayoutAuthenticatedIndexRoute
  LayoutAuthenticatedBookBookIdRoute: typeof LayoutAuthenticatedBookBookIdRoute
  LayoutAuthenticatedSeriesSeriesIdRoute: typeof LayoutAuthenticatedSeriesSeriesIdRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedPlannedRoute: LayoutAuthenticatedPlannedRoute,
  LayoutAuthenticatedReadRoute: LayoutAuthenticatedReadRoute,
  LayoutAuthenticatedSettingsRoute:
    LayoutAuthenticatedSettingsRouteWithChildren,
  LayoutAuthenticatedIndexRoute: LayoutAuthenticatedIndexRoute,
  LayoutAuthenticatedBookBookIdRoute: LayoutAuthenticatedBookBookIdRoute,
  LayoutAuthenticatedSeriesSeriesIdRoute:
    LayoutAuthenticatedSeriesSeriesIdRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutAuthRouteChildren {
  LayoutAuthLoginRoute: typeof LayoutAuthLoginRoute
  LayoutAuthRegisterChar123TokenChar125Route: typeof LayoutAuthRegisterChar123TokenChar125Route
}

const LayoutAuthRouteChildren: LayoutAuthRouteChildren = {
  LayoutAuthLoginRoute: LayoutAuthLoginRoute,
  LayoutAuthRegisterChar123TokenChar125Route:
    LayoutAuthRegisterChar123TokenChar125Route,
}

const LayoutAuthRouteWithChildren = LayoutAuthRoute._addFileChildren(
  LayoutAuthRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
  LayoutAuthRoute: typeof LayoutAuthRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
  LayoutAuthRoute: LayoutAuthRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  UUserNameRoute: UUserNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
